In [2]:
import numpy as np  # импорт библиотеки numpy

In [61]:
# Примеры создания массивов

In [62]:
list_a = np.array([1, 2, 3, 4, 5])  # массив из обычного списка
print(list_a)

b = [1, 2, 3, 4, 5]
list_b = np.array(b)
print(list_b)

[1 2 3 4 5]
[1 2 3 4 5]


In [63]:
list_aa = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])  # Создание двумерного массива
print(list_aa)

b = [1, 2, 3, 4, 5]
list_bb = np.array([b, [x**2 for x in b]])
print(list_bb)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3  4  5]
 [ 1  4  9 16 25]]


In [64]:
list_z = np.zeros(5)  # массив из 5 нулей
print(list_z, '\n')

list_zz = np.zeros((5, 5))  # массив 5х5 из нулей
print(list_zz, '\n')

list_zzz = np.zeros((2, 5, 5))  # массив 2x5х5 из нулей
print(list_zzz)

[0. 0. 0. 0. 0.] 

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [65]:
list_o = np.ones(5)  # массив из 5 нулей
print(list_o, '\n')

list_oo = np.ones((5, 5))  # массив из 5 нулей
print(list_oo, '\n')

list_ooo = np.ones((5, 5, 5))  # массив из 5 нулей
print(list_ooo)


[1. 1. 1. 1. 1.] 

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [66]:
list_oz = (np.indices((5, 5)).sum(axis=0)) % 2  # шахматная доска
print(list_oz)

[[0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]]


In [67]:
list_e = np.eye(5)  # единичная матрица
print(list_e)

list_obe = np.eye(5)[::-1]  # обратная единичная матрица
print(list_obe)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]


In [68]:
list_ar = np.arange(2, 16, 2)  # массив начиная с 2 заканчивая 16 (не вкл) с шагом 2
print(list_ar)

[ 2  4  6  8 10 12 14]


In [73]:
list_lin = np.linspace(0, 1, 25)  # 25 чисел от 0 до 1
print(list_lin)

[0.   0.04 0.08 0.12 0.17 0.21 0.25 0.29 0.33 0.38 0.42 0.46 0.5  0.54
 0.58 0.62 0.67 0.71 0.75 0.79 0.83 0.88 0.92 0.96 1.  ]


In [69]:
# Демонстрация атрибутов

In [86]:
# Создадим какой-нибудь массив
list_kakoi_to = np.random.randint(0, 100, size=(6, 6))
print(list_kakoi_to)

[[56 18 84 45 27  2]
 [95 81 33 55 24 46]
 [85 66 79 96 52 43]
 [ 8 41  3 13 43 27]
 [61 34 95 39 48 77]
 [74 21 19 82 98  2]]


In [88]:
print(list_kakoi_to.shape)  # Выводит размерность матрицы

(6, 6)


In [89]:
print(list_kakoi_to.dtype)  # Выводит тип данных массива

int32


In [90]:
print(list_kakoi_to.size)  # Количество элементов в массиве

36


In [93]:
print(list_kakoi_to.ndim)  # Количество вложенности/размерности

2


In [94]:
# Примеры индексирования и срезов

In [99]:
# Создание массива
list_kakoi_to2 = np.random.randint(0, 100, size=(3, 2, 5))
print(list_kakoi_to2)

[[[13 50 76 53 24]
  [67 56 70 42 66]]

 [[15 87  7  5 16]
  [86 83 97  1 37]]

 [[ 3 35 11 38 55]
  [53 55 52 52 46]]]


In [114]:
print(list_kakoi_to2[0])  # 1 элемент верхнего слоя
print(list_kakoi_to2[-3])

[[13 50 76 53 24]
 [67 56 70 42 66]]
[[13 50 76 53 24]
 [67 56 70 42 66]]


In [113]:
print(list_kakoi_to2[1][::-1]) # вывод в обратном порядке элементов 2 слоя под 1 индексом верхнего слоя
print(list_kakoi_to2[-2][::-1])

[[86 83 97  1 37]
 [15 87  7  5 16]]
[[86 83 97  1 37]
 [15 87  7  5 16]]


In [111]:
print(list_kakoi_to2[0, 0, 3])  # 4 элемент в 1 строке 1 массива
print(list_kakoi_to2[-3, -2, 3])

53
53


In [122]:
print(list_kakoi_to2[0][1][2:5])  #Элементы 3-5 в 1 массиве 2 строчке

[70 42 66]


In [115]:
# Примеры векторных операций

In [125]:
# Простенькие массивы для операций
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
print(a, '\n', b)

[1 2 3 4] 
 [5 6 7 8]


In [126]:
print(a+b)  # сложение

[ 6  8 10 12]


In [127]:
print(a-b)  # вычитание

[-4 -4 -4 -4]


In [138]:
print((a-b)*np.array([-1, -1, -1, -1])) # Положительный результат при вычитании
print(b-a)

[4 4 4 4]
[4 4 4 4]


In [139]:
print(a*b) # Умножение

[ 5 12 21 32]


In [140]:
print(a**b)  # элементы a в степени b

[    1    64  2187 65536]


In [141]:
# Примеры базовых статистиков

In [144]:
# Создадим массив
list_posledni = np.random.randint(0, 100, size=6)
print(list_posledni)

[33 18 68 60 68 75]


In [146]:
print(np.mean(list_posledni))  # Среднее значение

53.666666666666664


In [148]:
print(np.median(list_posledni))  # Медиана

64.0


In [149]:
print(np.sum(list_posledni))  # Сумма всех элементов

322


In [150]:
# Минимальное и максимальное значение
print(np.min(list_posledni))
print(np.max(list_posledni))

18
75


In [151]:
print(np.std(list_posledni))  # Стандартное отклонение

20.837999477450378
